build/root/usr/local/bin/run: download latest 'oc' client if missing from PATH
Prevent failures due to missing `oc` command (in pre-release):

```
/usr/local/bin/run: line 31: oc: command not found
error: failed to execute wrapped command: exit status 127
```